project:
  type: website
  output-dir: docs

website:
  title: "Connor Wolosewicz"
  description: "Recent GW graduate and aspiring urban planner"
  navbar:
    background: "#9cd0ff"
    foreground: "#2c3e50"
    right:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - href: projects.qmd
            text: Projects
          - href: writing.qmd
            text: Writing Samples
          - href: gis.qmd
            text: GIS Maps
          - href: blog.qmd
            text: DATS1001 Blog
          - href: extra.qmd
            text: Side Quests
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: lumen
    css: styles.css
    toc: false

