project:
  type: website
  output-dir: docs

website:
  title: "Connor Wolosewicz"
  description: "Recent GW graduate and aspiring urban planner"
  site-url: https://connor-wolosewicz.github.io/dats1001blog
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Writing
      - icon: github
        href: https://github.com/connor-wolosewicz

format:
  html:
    theme:
      - cerulean
    css: styles.css

editor: visual

