---
title: "Projects"
---

Applied and academic research on green infrastructure and urban ecology. 

### The Green Area Ratio: Nature Based Solutions Regulation in Washington DC

During my final semester as an undergraduate, I had the privilege of working with Dr. Melissa Keeley, Andrea Krug of the DOEE, and my peers Nils Berglund and Ali Sorrels, to comprehensively examine the performance of DC's Green Area Ratio (GAR). After over a decade of implementation, this performance-based zoning tool has resulted in the construction of approximately 184 ha of green infrastructure in privately-owned land. Using statistical and spatial analysis, we carried out the only systematic assessment of this type of regulatory tool that we know of, analyzing which landscape elements were used most often and where. Ultimately, the GAR proved to be a flexible and versatile tool for urban greening, with our data serving as a valuable case study for other jurisdictions considering a similar performance-based land-use planning approaches. (Currently under peer review at [MDPI's *Sustainability*](https://www.mdpi.com/journal/sustainability/special_issues/8ZNKQXMPNA))

